global.WRITE_IMAGE = 'WRITE_IMAGE';
global.LOAD_IMAGE_FILE = 'LOAD_IMAGE_FILE';
global.LOAD_IMAGE = 'LOAD_IMAGE';
global.GREYSCALE = 'GREYSCALE';
global.POSTERIZE = 'POSTERIZE'; //Deprecated
global.THRESHOLD = 'THRESHOLD';
global.FILL_HOLES = 'FILL_HOLES';
global.ELIMINATE_NOISE_PIXELS = 'ELIMINATE_NOISE_PIXELS';
global.FIND_BLOBS = 'FIND_BLOBS';
global.FIND_BLOB_BOUNDARIES = 'FIND_BLOB_BOUNDARIES';
global.FIND_REFERENCE_BLOB = 'FIND_REFERENCE_BLOB';
global.FIND_WINNER_BLOB = 'FIND_WINNER_BLOB'; //Deprecated
global.FIND_CLOSEST_BLOB = 'FIND_CLOSEST_BLOB';
global.DRAW_WINNER_BLOB = 'DRAW_WINNER_BLOB';
global.COLORIZE_BLOBS = 'COLORIZE_BLOBS'; //Debug
global.DRAW_BLOB_BOUNDARIES = 'DRAW_BLOB_BOUNDARIES'; //Debug




